name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: cargo test
      run: cargo test --tests -v
    - name: run test
      run: pwsh test.ps1

  test-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: cargo test
      run: cargo test --tests -v
    - name: run test
      run: pwsh test.ps1
